theme:
  debug: false
  delims:
    left: "{{"
    right: "}}"
  global:
#    - template1_loaded_globally
#    - template2_loaded_globally
  loaders:
    - dir: web/templates
      paths:
        base: # order is important
          - base